name: 'Reviewabot'
description: 'Reviewabot automates the process of creating a pull request review. It uses generative AI to create a review based on your instructions.'

inputs:
  open-api-key:
    description: 'Your OpenAPI Key'
    required: true
  reviewer-pat:
    description: 'The reviewers Private Access Token with permission to read source and write reviews'
    required: true
  owner:
    description: 'Name of the owner of the repository under review'
    required: false
    default: ${{github.repository_owner}}
  repository:
    description: 'Name of the repository under review'
    required: false
    default: ${{github.event.repository.name}}
  pr-number:
    description: 'The pull request number'
    required: false
    default: ${{github.event.number}}
    
runs:
  using: "composite"
  steps:
  - name: Setup .NET
    uses: actions/setup-dotnet@v4
    with:
      dotnet-version: 8.0.x

  - name: Clone Reviewabot Repository
    run: git clone --depth 1 --branch v1.0.1 https://github.com/simon-k/reviewabot.git
    shell: bash
    
  - name: Run Reviewabot
    shell: bash
    run: dotnet run --project reviewabot/src/Reviewabot/Reviewabot.Console/ --Owner=${{inputs.owner}} --Repo=${{inputs.repository}} --PrNumber=${{inputs.pr-number}} --OpenApiKey=${{inputs.open-api-key}} --githubpat=${{inputs.reviewer-pat}}
  